FROM docker.elastic.co/elasticsearch/elasticsearch:8.7.1

# Configuraciones adicionales si es necesario
# COPY <ruta_archivo_config> /usr/share/elasticsearch/config/<nombre_archivo_config>

# Comando para iniciar Elasticsearch
CMD ["elasticsearch"]
